name: GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /anime_chill/
          webRenderer: html
